version: '3'

services:
  seafile:
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-db}
      - MYSQL_PORT=${MYSQL_PORT-}
      - USE_EXISTING_DB=${USE_EXISTING_DB-}
      - MYSQL_USER=${MYSQL_USER-}
      - MYSQL_USER_PASSWD=${MYSQL_USER_PASSWD-}
      - MYSQL_USER_HOST=${MYSQL_USER_HOST-}
      - MYSQL_ROOT_PASSWD=${MYSQL_ROOT_PASSWD-}
      - CCNET_DB=${CCNET_DB-}
      - SEAFILE_DB=${SEAFILE_DB-}
      - SEAHUB_DB=${SEAHUB_DB-}