version: '3'

services:
  reverse-proxy:
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$HOST
      - SUBDOMAINS=${SUBDOMAINS-}
      - EXTRA_DOMAINS=${EXTRA_DOMAINS-}
      - STAGING=${STAGING-false}
      - VALIDATION=http
    volumes:
      - $SWAG_DIR:/config
    ports:
      - 443:443
      - 80:80
