version: '3'

services:
  seafile:
    image: franchetti/seafile-arm
    restart: always
    environment:
      - PUID=$PGID
      - PGID=$PUID
      - TZ=$TZ
      - SERVER_IP=$SERVER_IP
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD
      - ENABLE_TLS=$ENABLE_TLS
    volumes:
      - media:/shared/media
      - $SEAFILE_CONF_DIR:/shared/conf
      - $SEAFILE_LOGS_DIR:/shared/logs
      - $SEAFILE_DATA_DIR:/shared/seafile-data
      - $SEAFILE_SEAHUB_DIR:/shared/seahub-data

  x-proxy-volumes:
    volumes:
      - media:/shared/media
      - $SEAFILE_SEAHUB_DIR:/shared/seahub-data

  swag:
    extends: x-proxy-volumes
    image: linuxserver/swag
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$SERVER_IP
      - VALIDATION=http
    volumes:
      - $SWAG_DIR:/config

  noswag:
    extends: x-proxy-volumes
    image: nginx
    restart: always
    volumes:
      - ./nginx/seafile.noswag.conf:/etc/nginx/conf.d/seafile.conf:ro