version: '3'

services:
  reverse-proxy:
    restart: always
    depends_on:
      - seafile
    volumes:
      - media:/shared/media
      - ${SEAFILE_SEAHUB_DIR}:/shared/seahub-data
    networks:
      - seafile