version: '3'

services:
  seafile:
    image: franchetti/seafile-arm
    restart: always
    environment:
      - PUID=${PGID-""}
      - PGID=${PUID-""}
      - TZ=${TZ-""}
      - SQLITE=${SQLITE-""}
      - SERVER_IP=${URL-""}
      - PORT=${PORT-""}
      - SEAHUB_PORT=${SEAHUB_PORT-""}
      - FILESERVER_PORT=${FILESERVER_PORT-""}
      - USE_HTTPS=${USE_HTTPS-""}
      - SEAFILE_ADMIN_EMAIL=${SEAFILE_ADMIN_EMAIL-""}
      - SEAFILE_ADMIN_PASSWORD=${SEAFILE_ADMIN_PASSWORD-""}
    volumes:
      - media:/shared/media
      - $SEAFILE_CONF_DIR:/shared/conf
      - $SEAFILE_LOGS_DIR:/shared/logs
      - $SEAFILE_DATA_DIR:/shared/seafile-data
      - $SEAFILE_SEAHUB_DIR:/shared/seahub-data
    networks:
      - seafile

volumes:
  media:

networks:
  seafile: