version: '3'

services:
  reverse-proxy:
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$URL
      - VALIDATION=http
    volumes:
      - $SWAG_DIR:/config
    ports:
      - 443:443
      - 80:80