version: '3'

services:
  seafile:
    image: franchetti/seafile-arm
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - SERVER_IP=your.domain
      - SEAFILE_ADMIN_EMAIL=you@your.email
      - SEAFILE_ADMIN_PASSWORD=secret
      - ENABLE_TLS=1
      - MYSQL_HOST=db
      - MYSQL_USER_PASSWD=secret
      - MYSQL_ROOT_PASSWD=secret
    volumes:
      - ./seafile:/shared
    depends_on:
      - db

  db:
    image: linuxserver/mariadb
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Europe/Zurich
    volumes:
      - ./db:/config
      
  reverse-proxy:
    image: linuxserver/swag
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - URL=your.domain
      - VALIDATION=http
    volumes:
      - ./reverse-proxy:/config
      - ./seafile:/shared
    ports:
      - 443:443
      - 80:80
