version: '3'

services: 
  reverse-proxy:
    image: nginx
    restart: always
    volumes:
      - ./nginx/seafile.conf:/etc/nginx/conf.d/seafile.conf:ro
      - ./seafile:/shared
    ports:
      - "80:80"
