version: '3'

services: 
  reverse-proxy:
    image: nginx
    restart: always
    volumes:
      - media:/shared/media
      - ./seafile/seahub-data:/shared/seahub-data
      - ./nginx/seafile.testing.conf:/etc/nginx/conf.d/seafile.conf:ro
    ports:
      - 80:80