version: '3'

services:
  seafile:
    image: franchetti/seafile-arm
    restart: always
    environment:
      - PUID=$PGID
      - PGID=$PUID
      - TZ=$TZ
      - SERVER_IP=$SERVER_IP
      - SEAFILE_ADMIN_EMAIL=$SEAFILE_ADMIN_EMAIL
      - SEAFILE_ADMIN_PASSWORD=$SEAFILE_ADMIN_PASSWORD
      - ENABLE_TLS=$ENABLE_TLS
      - SQLITE=$SQLITE
      - MYSQL_HOST=$MYSQL_HOST
      - MYSQL_USER_PASSWD=$MYSQL_USER_PASSWD
      - MYSQL_ROOT_PASSWD=$MYSQL_USER_PASSWD
    volumes:
      - media:/shared/media
      - $SEAFILE_CONF_DIR:/shared/conf
      - $SEAFILE_LOGS_DIR:/shared/logs
      - $SEAFILE_DATA_DIR:/shared/seafile-data
      - $SEAFILE_SEAHUB_DIR:/shared/seahub-data
      - $SEAFILE_SQLITE_DIR:/shared/sqlite

      
  reverse-proxy:
    image: linuxserver/swag
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - URL=$SERVER_IP
      - VALIDATION=http
    volumes:
      - media:/shared/media
      - $SEAFILE_SEAHUB_DIR:/shared/seahub-data
      - $SWAG_DIR:/config
    ports:
      - 443:443
      - 80:80

volumes:
  media:
