version: '3'

services: 
  reverse-proxy:
    image: nginx
    restart: always
    volumes:
      - media:/shared/media
      - $SEAFILE_SEAHUB_DIR:/shared/seahub-data
      - ./nginx/seafile.noswag.conf:/etc/nginx/conf.d/seafile.conf:ro
    ports:
      - 80:80